# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-24 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='l_name',
        ),
    ]
