# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-24 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0002_auto_20190524_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='duration',
        ),
    ]
